### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by cweagans** [vaimo/composer-patches#14]
I'm not sure I understand why you forked this. I don't see a single issue or PR open from @allanpaiste in the main repo.

In any case, I'd love some assistance maintaining the original plugin if you're interested. 2.x is well in swing and will be adding substantial test coverage and functionality to the plugin, so if you're interested, now is the time to jump in.

**Comment by allanpaiste** [comment]
The repository first got forked due to wanting a fast fix to a problem that we were facing internally. We were in situation of having to maintain tens of projects in parallel which were on different versions and required different version of patches for same fixes. On the moment of forking, the main module did not have support for having patches in packages in a way that it required targeted modules to be already installed (which was not always the case as the installation order did not make every module depend on patches module).

Everything else followed due to being faced with patch maintenance, creation and testing in daily basis (more declaration syntaxes, base paths, multiple patch files, 'patch' command, etc).

So there's the "why".

Why there are no pull-requests? From where I stand, it does look like you're after simplicity, and I think simplicity in the context of a Magento project just did not cut it for us. Most of the features in this repository target adding in things that I personally was not sure you wanted.

This repo and all that's currently in it grew out from painful necessity to go forward with the projects that we run in-house (+ being constantly involved with patch maintenance). Nothing more.

**Comment by cweagans** [comment]
I hope that 2.0.0 has the required flexibility for you. I would love your input on where there are shortcomings as things progress. If nothing else, a small time investment on your part might mitigate the need for this plugin to exist.

Thanks for the explanation.
