### ISSUE TITLE
Patch file in root Folder

### ISSUE THREAD

**Issue by ucola** [vaimo/composer-patches#17]
hi all

We want do execute a patch for a .htaccess file, which is in the root of the webroot folder. We use https://github.com/drupal-composer/drupal-scaffold and this module copy the .htaccess to the root folder. But if we try to execute a patch drupal-composer/drupal-scaffold it dosent works. Any ideas how we can solve this problem?

**Comment by allanpaiste** [comment]
Hi,

There WAS no real good way to do this as the module worked off of install paths of the packages (one exception being the fact that bundled patches -- that target more than one package -- were applied against vendor folder).

Since 3.33.0 and 4.2.0, things have somewhat improved.

So in your case, throw in the configuration option described here:

https://github.com/vaimo/composer-patches#patches-patch-applier-cwd-options

Then you should get the result you're after.

**Comment by ucola** [comment]
We test it but dosent works, the patch exists on this path...

> [Vaimo\ComposerPatches\Exceptions\PatchFailureException]`
> Cannot apply patch /home/user/www/webroot/core_prebackup/htaccess.patch

> "drupal-composer/drupal-scaffold": {
> "Doing something cool with .htaccess": {
> "source": "core_prebackup/htaccess.patch",
> "type": "project"
> }
> }
> "extra": {
>  "patches": {
>   "drupal-composer/drupal-scaffold": {
>    "Doing something cool with .htaccess": {
>     "source": "core_prebackup/htaccess.patch",
>     "type": "project"
>    }
>   }
>  }
> }

**Comment by allanpaiste** [comment]
Note the "type" in your configuration, which in my example is "cwd"
